from _typeshed import Incomplete

RESPONSE_TIMEOUT: int
RETRY_AFTER_TIMEOUT: int
VALID_SECURITY_TYPES: Incomplete
VALID_DATA_SOURCES: Incomplete
BASE_URL: str
FUNDAMENTALS_BASE_URL: str
JUSTETF_BASE_URL: str
NASDAQ_BASE_URL: str
DIGRIN_BASE_URL: str
MACROTRENDS_BASE_URL: str
INCOME_STATEMENT_COLUMNS: Incomplete
CASH_FLOW_COLUMNS: Incomplete
BALANCE_SHEET_COLUMNS: Incomplete
FINANCIALS_COLUMNS: Incomplete
