[package]
name = "crud_insertable"
version = "0.1.0"
edition = "2024"

[dependencies]
proc-macro2 = "1.0"
syn = { version = "2.0", features = ["full"] }
quote = "1.0"
convert_case = "0.8.0"

[lib]
proc-macro = true
